### ISSUE TITLE
Feature (?): Framed Network Cable for Vertical Runs

### ISSUE THREAD

**Issue by papaworld** [Commoble/morered#15]
Really love and appreciate your work and advancements with MoreRed. The Network Cable and all other items in your mod is Super, like ProjectRed.

Are you considering a framed version for free-standing vertical wiring? Maybe not necessary 'cause Bundled Cable Relay Plate and cable spool work to perform the same task,

Nice mod, works superior and long awaited.

Thank you

**Comment by Commoble** [comment]
There are currently no intentions to add free-standing vertical wiring for that very reason -- the blockless wires already act like that, more or less
