### ISSUE TITLE
Add ComputerCraft support, particularly for the bundled signals

### ISSUE THREAD

**Issue by Commoble** [Commoble/morered#19]

**Comment by MJTheOne** [comment]
Yes this! Just created an account on curseforge to be able to comment when I saw this. I wish I could help, but I have no real experience with Java / MC mods.

**Comment by ChrisChrome** [comment]
Bump, I'd love to see this

**Comment by Commoble** [comment]
Made a block in a separate mod that connects More Red cables to computercraft computers.

https://www.curseforge.com/minecraft/mc-mods/more-red-computercraft-integration

It's currently stuck in curseforge approval limbo (so that link won't work for most people at the time of this comment) but the sources can be checked out here

https://github.com/Commoble/morered_computercraft_integration
