### ISSUE TITLE
v1.0.0.0 : Diode outputs strong signal strength 15

### ISSUE THREAD

**Issue by OfficialStamper** [Commoble/morered#2]
If a diode receives a redstone signal less than 15, it will output a strength of 15 regardless, similar to a repeater.

Seeing as we already repeaters (albeit, the don't mount vertically), could the diode output a signal 1 less than the input?  i.e. if input strength is 10, output strength would be 9, as if the diode was a piece of inline redstone dust.

**Comment by Commoble** [comment]
This was intentional and is unlikely to change.

That being said, they don't strictly outclass repeaters; repeaters have a long, adjustable delay, which nothing in More Red does at the moment.

**Comment by OfficialStamper** [comment]
I guess I'm just looking for a vertical mountable equiv of a Comparator (without the compare or subtract), just to maintain an analogue signal.  Everything in MoreRed currently works with strong signals only (output).

A delay (repeater) tile would be cool also.

Some food for thought, I will leave it with you to decide if they are something you want to add (or not).

Lovin the mod as it is so far.  Great job.  A welcome addition to the 1.15.2 mod set.  Cheers

**Comment by mopsyd** [comment]
I like having an option to relay a full strength signal without a delay. Even on the lowest setting, the vanilla repeater has a delay. It's also useful in cross-mod configurations (ahem, RFTools wireless redstone, which connects to logic plates but not regular wires for some reason). Were this to change, there would not be an option for a lagless circuit, and analog measurements would be slightly easier in niche circumstances. Were it kept the same, there is a lagless circuit option, and analog niche setups need only one additional block worth of redstone to get a value of 14 from full power.
