### ISSUE TITLE
Red Alloy Wire not connecting.

### ISSUE THREAD

**Issue by goldern** [Commoble/morered#20]
Red Alloy Wire from More Red does not connect to Tinker's Construct Seared faucet, nor RFTools timers.

[https://i.imgur.com/WeyCpwW.png](url)

[https://imgur.com/4nnGHer](url)

More Red Version: morered-1.16.5-2.1.0.3
Tinker's Construct Version: TConstruct-1.16.5-3.0.3.126
RFTools Version: rftoolsutility-1.16-3.0.25

**Comment by Commoble** [comment]
Reopen issue if it still occurs in 1.22
