### ISSUE TITLE
Add an option for no loss cables or a bundled cable repeater

### ISSUE THREAD

**Issue by Legion7766** [Commoble/morered#22]
So it has been a while since i use bundled cables in project red but i thought that they didn't lose redstone signal strength throughout the line, I could be wrong though.  However, I have three possible solutions to this issue.

1) A config option to allow for lossless redstone signal transfers when using bundled cables, colored cables can still lose signal strength or not, could be an additional config as well.

2) Add an upgraded version of the bundled cable that is lossless vs the standard version which can lose signal strength.  Again colored cables could benefit from this upgraded cable version also.

3) Add a bundled cable repeater so that you can reset the signal strength of all the colors in a bundled cable without having to break each color being used out individually.

**Comment by Commoble** [comment]
2.1.1.0 adds the bitwise diode which fulfills the repeater function
