### ISSUE TITLE
Server Freeze when Red Alloy Wire is used with Redstone Dust

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Commoble/morered#24]
Minecraft 1.16.5
Forge 36.1.32
More Red morered-1.16.5-2.1.1.0

In my Modpack [99 Mods on the Wall](https://www.curseforge.com/minecraft/modpacks/ninety-nine-mods-on-the-wall/files/3293489) I had placed a Red Alloy Wire under a block with a pressure plate and the wire did not get the Redstone signal when the pressure plate was stepped on. I replaced the last piece of wire with Redstone dust and it worked, but the server froze. It did not crash, but eventually timed me out and still show all players as logged in, when in fact all had timed out. I had to force kill the server and restart it. I warned the other players I was going to test this again, and the exact same thing happened when I stepped on the pressure plate. There was no crash, hence no crash report. Though I have included the log files.

[latest.log](https://github.com/Commoble/morered/files/6704715/latest.log)
[debug.log](https://github.com/Commoble/morered/files/6704716/debug.log)

**Comment by Commoble** [comment]
Can you describe the positions of the blocks here in more detail?

**Comment by ClaudiusMinimus** [comment]
I also found out this issue only applies to servers. In singleplayer it worked fine. I hope the image provides the detail you requested.

![image](https://user-images.githubusercontent.com/17887664/123478689-012a0b80-d5bd-11eb-8875-30f187e0fb02.png)

**Comment by ClaudiusMinimus** [comment]
Also found that not only pressure plates don't work with Red Alloy Wire, but Tripwire hooks do not work as well

**Comment by Commoble** [comment]
I'm unable to reproduce this:

https://cubicinterpolation.net/images/minecraft/plate_doesnt_crash_morered_0.png

Even on a dedicated server, using the redstone dust under the pressure plate doesn't freeze the server for me. There might be an interaction with another mod causing your server freeze? I wouldn't be able to help further without knowing which mod was causing the problem (try removing performant, it does weird things that can break other mods sometimes)

**Comment by ClaudiusMinimus** [comment]
I have had a lot of real-life things happening, so I have not been able to identify the crash. However, that is only one of the issues identified in this thread. The other issue (maybe this should be a separate issue report) is that the Red Alloy Wire does not seem to work under a pressure plate or with a tripwire. Please let me know if you want this issue moved to a separate issue report.

**Comment by Commoble** [comment]
> The other issue (maybe this should be a separate issue report) is that the Red Alloy Wire does not seem to work under a pressure plate or with a tripwire

Oh, no, that's intentional -- the wires can only conduct or receive power through solid blocks if they're directly attached to it

**Comment by Commoble** [comment]
New wiring system in 1.21.3+ should prevent infinite loops
