### ISSUE TITLE
Incorrect cable rendering with sodium

### ISSUE THREAD

**Issue by Garagoth** [Commoble/morered#26]
Hi!

With Sodium Reforged the cables are rendering incomplete:
![2021-10-03_21 55 06](https://user-images.githubusercontent.com/916161/135769665-eb941b5f-274e-4aa9-a7eb-3dc8cc9246b5.png)

Same happens with Halogen (also a sodium forge fork).

**Comment by kirinnee** [comment]
Happens with magnesium too!

**Comment by musznik** [comment]
and Rubidium

**Comment by TheFlameFish** [comment]
It's probably more of an issue with Sodium. I think the More Red devs _might_ be able to fix it since sodium is open-source. But considering this was opened a year ago. I doubt they will.
