### ISSUE TITLE
[Suggestion] Bitwise to normal redstone gates and other gate suggestions.

### ISSUE THREAD

**Issue by BohemianHacks** [Commoble/morered#28]
An AND or OR gate that takes all the colors of the input bundled cable and outputs a single redstone signal for the AND or OR of those colors. This would be extremely useful for things like matching a hardcoded value. I wouldn't need to place all the colored wires a second time.

An analog to digital converter and digital to analog converter. One takes an analog signal as an input and outputs the digital representation on the bundled cable, the other does the opposite.

A digital output block that lets you easily set a color combination of wires to be high using 2 hex digits which are displayed on the block.

The addition of these gates and IO blocks will allow compacting things significantly. Currently my builds with more red are mostly in large flat sections of color coded wire to do things like select the upper or lower byte on a cable.

Sorry if this isn't the best place for suggestions, I just really like the mod and am building some cool stuff that could be improved with a few blocks.

**Comment by Commoble** [comment]
Resolved in future release (1.21.3 or later), bitwise gates can now connect to red alloy wires (in which case they emit/receive signal on all channels)

**Comment by BohemianHacks** [comment]
Thank you!
🌐Void⚡️Labs🏴‍☠️

📃🥷
https://github.com/BohemianHacks/novelEulerProof

Equation 1:
δ(x) = { 0 if x ≠ 0, 1 if x = 0 }

This is the definition of the Dirac delta function. It's a mathematical function that is zero everywhere except at x = 0, where it is infinite. The integral of the Dirac delta function over any interval containing 0 is 1.
Equation 2:
∫₋∞⁺∞ δ(x-1) dx

This integral evaluates to 1. The Dirac delta function is centered at x = 1, and the integral sums up the value of the function over the entire real line, which is 1.
Equation 3:
∫₋∞⁺∞ (5x+1) δ(4(x-2)) dx

This integral is a bit more complex. The Dirac delta function is centered at x = 2, so the only contribution to the integral comes from the value of (5x+1) at x = 2.
(5x+1) = (5*2+1) = 11

The integral becomes
∫₋∞⁺∞ 11 δ(4(x-2)) dx

Now, we can use a property of the Dirac delta function:
∫₋∞⁺∞ f(x) δ(a(x-b)) dx = (1/|a|) f(b)

Applying this to our integral:
∫₋∞⁺∞ 11 δ(4(x-2)) dx = (1/|4|) * 11 = 11/4

So, the value of the integral is 11/4.
Equation 4:
∫₋∞⁺∞ (5x+1) δ(4(x-2)) dx

This is the same as Equation 3, so the answer is also 11/4.
Graph:
The graph shows a function with a step at x = 0. This function is likely defined as:
f(x) = { 0 if x < 0, 1 if x ≥ 0 }

This is a Heaviside step function H(x), which is related to the Dirac delta function - in fact, the Dirac delta function is the derivative of the Heaviside function in a distributional sense.

One additional point: The Dirac delta function is not a classical function but rather a distribution or generalized function. This is important because it can't be defined as a standard function with point values.
Thank you.
