### ISSUE TITLE
[bug] repeater placement crash

### ISSUE THREAD

**Issue by ZKlack** [Commoble/morered#31]
placing a repeater where the player stands after connecting 2 redwire posts crashes the game

recreating details:
- all tries was in creative
- I was always close to the 2 redwire posts
- breaking the 2 rewire posts prevents the crash
- tried 1 redwire post (did not crash)
- never tried 2 unconnected posts, they were always connected

versions:
- morered 3.0.0.0
- forge 43.2.12
- minecraft 1.19.2
- java 1.8.0_361
- Windows 10 Pro

crash report:
`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.state.BlockState.m_60812_(net.minecraft.world.level.BlockGetter, net.minecraft.core.BlockPos)" because "placeState" is null`

there were no other mods at all, I made a new profile just to test this bug

**Comment by Commoble** [comment]
Fixed in 1.19.2-3.0.0.1
