### ISSUE TITLE
[Suggestion] Fabric support

### ISSUE THREAD

**Issue by PatentOwl** [Commoble/morered#32]
Well. as it says: I beg for fabric support. It would be a dream to see it in fabric. this mod is the best logic mod ive ever seen! And we all need it in fabric.

**Comment by Commoble** [comment]
The mod is open-source so anyone who wants to try porting it to fabric is welcome to

**Comment by PatentOwl** [comment]
Okay thanks. Now sounds stupid but i cant so that 😆

Joseph B ***@***.***> schrieb am Sa., 16. Sept. 2023, 14:45:
