### ISSUE TITLE
More Red automatically adds JumboFurnace mod

### ISSUE THREAD

**Issue by logan-mcduffie** [Commoble/morered#33]
As the title says. Running the latest Forge jar of More Red on 1.20.1. I do not have the jumbomod jar installed, I've quadruple checked. When I add the More Red mod to my modpack, it adds jumbo furnace. If it's intended to be a hard dependency, that's fine. But at least advertise it correctly on the curseforge page:

"For best results, we recommend using More Red with [Jumbo Furnace](https://www.curseforge.com/minecraft/mc-mods/jumbo-furnace) (though it also works perfectly fine without it)"

**Comment by Commoble** [comment]
My bad, I made it a hard dependency in 1.20.1 and forgot to update the description. Fixed

**Comment by lonevox** [comment]
Would it be possible for this hard dependency to be removed and making it a conditional recipe instead? So if Jumbo Furnace is included it loads the red alloy ingot jumbo smelting recipe, and if it isn't included it loads a furnace recipe. This would be helpful for me as Jumbo Furnace doesn't make sense in my modpack but I would like to include More Red.

https://docs.minecraftforge.net/en/1.20.x/datagen/server/recipes/#conditional-recipes
