### ISSUE TITLE
[Suggestion] Add a configuration to disable Jumbo Furnaces

### ISSUE THREAD

**Issue by omgimanerd** [Commoble/morered#35]
Hi, I'm working on a modpack at the moment and I was a little surprised by the fact that More Red also bundled Jumbo Furnaces in its jar. I saw from your curseforge comment that it's possible to disable the multiblock from spawning by doing:
```
// data/jumbofurnace/tags/blocks/jumbo_furnaceables.json
{
	"replace": true,
	"values":
	[]
}
```
but afaict the recipes will still appear in JEI. I will probably be manually hiding these with KubeJS code, but would you consider releasing a 1.20.1 version without them bundled them together anymore since its trivial to install them separately? Thanks for your time.

**Comment by Commoble** [comment]
As of 1.21, jumbo furnace will no longer be bundled with More Red, reverting to the old behavior where red alloy ingots will be crafted at the crafting table if jumbo furnace is not installed (the recipes can still be overridden with datapacks).

**Comment by DaddySpin** [comment]
If I am understanding this correctly if you are using 1.20.1 you have to disable the multiblock with the above json file and then use some method like KubeJS to remove the recipe with it's id?
