### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by SubordinalBlue** [Commoble/morered#39]
Over on the Craftoria official servers, we are getting server crashes, sometimes hours apart, sometimes more frequent, that have _more red_ spammed in the crash reports.

At the moment, I don't have coincident observations to give; will update this issue if we find them.

[crash-2024-09-20_20.05.52-server.txt](https://github.com/user-attachments/files/17081936/crash-2024-09-20_20.05.52-server.txt)
[crash-2024-09-20_00.28.24-server.txt](https://github.com/user-attachments/files/17081934/crash-2024-09-20_00.28.24-server.txt)
[crash-2024-09-20_15.27.57-server.txt](https://github.com/user-attachments/files/17081935/crash-2024-09-20_15.27.57-server.txt)
[crash-2024-09-20_20.17.28-server.txt](https://github.com/user-attachments/files/17081938/crash-2024-09-20_20.17.28-server.txt)

**Comment by Commoble** [comment]
Currently working on a rewrite for 1.22 which should prevent this sort of infinite loop from happening, but if you can determine the exact setup of blocks which causes this then I might be able to fix this in 1.21 as well

**Comment by Commoble** [comment]
New wiring system in future release (1.21.3+) should be immune to infinite loops
