### ISSUE TITLE
Sodium breaks cable connections visually. 

### ISSUE THREAD

**Issue by Vartis** [Commoble/morered#43]
Just morered.
![2024-11-25_14 30 24](https://github.com/user-attachments/assets/2a2192df-9651-4c41-b4f0-df32a7736b6f)
With sodium
![2024-11-25_14 31 53](https://github.com/user-attachments/assets/0e5160c5-9dbd-48d5-9426-cc1829f738e9)

Redstone still functions as expected and you can see that they are connected but just invisible.
![2024-11-25_14 31 59](https://github.com/user-attachments/assets/73b43d6e-92f8-45c0-a186-fe02de7d30c1)

Minecraft version : 1.21.1
Neoforge version : 21.1.79
MoreRed version : morered-1.21.1-6.0.0.3
Sodium version : sodium-neoforge-0.6.0+mc1.21.1

Sorry if this is technically a sodium issue but other mods seem to be ok with connecting textures/objects.

**Comment by Commoble** [comment]
Sodium replaces a lot of the game's rendering code and I can't really do anything about it

**Comment by Mrbysco** [comment]
Workaround: use Embeddium

**Comment by MaxNeedsSnacks** [comment]
Just confirmed that the issue does indeed not seem to occur with Embeddium, so uh... yeah, I guess just use that :p

**Comment by Commoble** [comment]
no I rewrote everything specifically because of redstone changes in later versions that are not present in 1.21.1, and I don't know which part of the rewrite fixed the sodium issue

**Comment by Lolothepro** [comment]
caused by https://github.com/Sinytra/ForgifiedFabricAPI/issues/255

**Comment by SiriosDev** [comment]
> caused by [Sinytra/ForgifiedFabricAPI#255](https://github.com/Sinytra/ForgifiedFabricAPI/issues/255)

wrong, or at least out of topic

**Comment by Lolothepro** [comment]
> > caused by [Sinytra/ForgifiedFabricAPI#255](https://github.com/Sinytra/ForgifiedFabricAPI/issues/255)
> 
> wrong, or at least out of topic

Why? Sodium uses the Forgified Fabric API for rendering.

> this happens because the wrong `ModelData` gets passed to children of `MultiPartBakedModel`, the root `ModelData` gets saved in `BlockRenderer#renderModel`, then the model and its children are traversed by fabric api's `emitBlockQuads` which doesn't handle `ModelData`, then it gets back to sodium in `bufferDefaultModel` and all models are given the saved root `ModelData`, i was able to hackfix this by mixining into the fabric api's `MultipartBakedModelMixin#emitBlockQuads` which makes the wires render but now they have weird lighting, idk if this is related and what the correct way to fix all of this would be

andrew

It has been determined that this is caused by Forgified Fabric API.

**Comment by SiriosDev** [comment]
> It has been determined that this is caused by Forgified Fabric API.

even without sinytra installed?

**Comment by Lolothepro** [comment]
> > It has been determined that this is caused by Forgified Fabric API.
> 
> even without sinytra installed?

yes

**Comment by SiriosDev** [comment]
> > > It has been determined that this is caused by Forgified Fabric API.
> > 
> > 
> > even without sinytra installed?
> 
> yes

ok, my bad
