### ISSUE TITLE
Old versions on Modrinth

### ISSUE THREAD

**Issue by Alter73** [Commoble/morered#45]
The fact is that new versions of the mod have appeared only on CurseForge, but they still do not exist on Modrinth. Please upload them to Modrinth as well.

**Comment by Commoble** [comment]
no I stopped uploading them to modrinth

**Comment by Alter73** [comment]
Pity, may I know why? It is still used in some of my builds, but now, unfortunately, it is not updated. Anyway, thanks for the reply.

**Comment by Commoble** [comment]
Uploading to both curseforge and modrinth is more effort than uploading to just curseforge

Curseforge gives me $500/month and modrinth only gives me like a dollar a month

Also More Red isn't save-compatible across major mc versions so it's a moot point
